### ISSUE TITLE
生成豆瓣图书报错

### ISSUE THREAD

**Issue by frankwuzp** [icue/DoubanImageWall#1]
- 错误信息：
```
Error: No image to process. HTTP request may have been blocked.
```

- 现有配置：
```
python image_wall.py -i=<id隐去> -m='book' -c=10 -r=8 -o=0 -rd=False -s=True
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.0/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.0/x64/lib
```

豆瓣电影生成正常，是豆瓣图书封接口的意思吗？
